-- down migration script
DROP TABLE IF EXISTS Log;

DROP TABLE IF EXISTS JsInfo;
DROP TABLE IF EXISTS UserAgent;
DROP TABLE IF EXISTS Referrer;
DROP TABLE IF EXISTS IpAddress;
DROP TABLE IF EXISTS Bicmid;
DROP TABLE IF EXISTS User;
